name: Build Linux Kernel

on:
  push

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Set up QEMU
      run: sudo apt-get install -y qemu qemu-user-static binfmt-support

    - name: Build Kernel
      run: |
        git clone https://github.com/torvalds/linux.git
        cd linux
        make defconfig
        make -j $(nproc)
