name: Lint code
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2.4.2
    - step-summary: true
