name: Linux Kernel Lint Bot

on:
  workflow_dispatch:

jobs:
  lint_bot:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck

    - name: Scan for linting issues
      run: |
        for file in $(find . -name "*.c" -o -name "*.h"); do
          cppcheck --enable=all --inconclusive --force --inline-suppr --quiet --error-exitcode=0 --suppress=missingIncludeSystem $file
        done

    - name: Create issues
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "[Lint Bot] ${{ github.event.inputs.file_name }} ${{ github.event.inputs.issue_name }}"
        body: |
          File Path: ${{ github.event.inputs.file_path }}
          Issue: ${{ github.event.inputs.issue_name }}
          Line: ${{ github.event.inputs.line_number }}
        labels: Bot