name: Lint code
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        with:
          style: file
          step-summary: true
